# -*- coding: utf-8 -*-
"""CV_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aNAPYjutDpjx6EUeoF60eIvrtdMJYebO
"""

# @title Imports and Dependencies

!pip install torch torchvision torchaudio --upgrade --quiet
!pip install diffusers transformers accelerate safetensors opencv-python pillow --quiet
!pip install timm --quiet

import torch
import cv2
import numpy as np
from PIL import Image
from diffusers import StableDiffusionControlNetPipeline, ControlNetModel
from torchvision import transforms

# @title Pipeline 1
# ===================================================
#  INSTALL DEPENDENCIES
# ===================================================
!pip install torch torchvision torchaudio --upgrade --quiet
!pip install diffusers transformers accelerate safetensors opencv-python pillow timm --quiet

# ===================================================
#  IMPORT LIBRARIES
# ===================================================
import torch
import cv2
import numpy as np
from PIL import Image
from diffusers import StableDiffusionControlNetPipeline, ControlNetModel

# ===================================================
#  DEVICE CONFIG
# ===================================================
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# ===================================================
#  LOAD MiDaS DEPTH MODEL
# ===================================================
midas = torch.hub.load("intel-isl/MiDaS", "DPT_Hybrid")
midas.to(device)
midas.eval()

midas_transforms = torch.hub.load("intel-isl/MiDaS", "transforms")
transform = getattr(midas_transforms, "dpt_transform", midas_transforms.default_transform)

def get_depth_map(image_path):
    """Generate normalized depth map from layout or room image."""
    img = Image.open(image_path).convert("RGB")
    img_np = np.array(img)  # convert PIL → NumPy
    input_batch = transform(img_np).to(device)

    with torch.no_grad():
        prediction = midas(input_batch)
        prediction = torch.nn.functional.interpolate(
            prediction.unsqueeze(1),
            size=img.size[::-1],
            mode="bicubic",
            align_corners=False,
        ).squeeze()

    depth = prediction.cpu().numpy()
    depth = cv2.normalize(depth, None, 0, 255, cv2.NORM_MINMAX)
    depth = depth.astype(np.uint8)
    depth_img = cv2.cvtColor(depth, cv2.COLOR_GRAY2BGR)
    return depth_img

# ===================================================
#  LOAD CONTROLNET + STABLE DIFFUSION
# ===================================================
print("Loading ControlNet & Stable Diffusion...")

# Load ControlNet first
controlnet = ControlNetModel.from_pretrained("lllyasviel/sd-controlnet-depth")
# Cast dtype if needed
if device.type == "cuda":
    controlnet = controlnet.to(torch.float16)

# Load Stable Diffusion pipeline
pipe = StableDiffusionControlNetPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    controlnet=controlnet
)
pipe.to(device)
if device.type == "cuda":
    pipe.enable_xformers_memory_efficient_attention()
pipe.enable_attention_slicing()

# ===================================================
#  GENERATION FUNCTION
# ===================================================
def generate_interior_design(layout_path, prompt, output_path="interior_design.png"):
    print("Generating depth map...")
    depth_map = get_depth_map(layout_path)

    print("Generating interior design from prompt...")
    depth_map = cv2.resize(depth_map, (512, 512))

    result = pipe(
    prompt=prompt,
    image=Image.fromarray(depth_map),
    num_inference_steps=20,
    guidance_scale=7.5
    )

    img = result.images[0]
    img.save(output_path)
    print(f" Design saved as {output_path}")
    return img

# ===================================================
#  inference
# ===================================================
layout_image_path = "rooms_1.jpg"  # upload our image path here
prompt = "modern luxury living room with warm wood tones and natural light" # kind of chnage to images
output_image_path = "final_interior.png" # path of chnaged image

image = generate_interior_design(layout_image_path, prompt, output_image_path)
image.show()

from PIL import Image
import matplotlib.pyplot as plt

# Paths to your images
original_path = layout_image_path          # your original layout image path
generated_path = output_image_path         # the generated output ("final_interior.png")

# Load both images
original_img = Image.open(original_path).convert("RGB")
generated_img = Image.open(generated_path).convert("RGB")

# Create a side-by-side display
plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
plt.imshow(original_img)
plt.title("Original Layout")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(generated_img)
plt.title("Generated Interior Design")
plt.axis("off")

plt.tight_layout()
plt.show()

import torch
import cv2
import numpy as np
from PIL import Image
from diffusers import StableDiffusionControlNetPipeline, ControlNetModel
import torchvision
import matplotlib.pyplot as plt

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# ---------------------- Depth Map ----------------------
midas = torch.hub.load("intel-isl/MiDaS", "DPT_Hybrid")
midas.to(device).eval()
midas_transforms = torch.hub.load("intel-isl/MiDaS", "transforms")
transform = getattr(midas_transforms, "dpt_transform", midas_transforms.default_transform)

def get_depth_map(image_path, resize=(512,416)):
    img = Image.open(image_path).convert("RGB")
    img_np = np.array(img)
    input_batch = transform(img_np).to(device)

    with torch.no_grad():
        prediction = midas(input_batch)
        prediction = torch.nn.functional.interpolate(
            prediction.unsqueeze(1),
            size=resize[::-1],
            mode="bicubic",
            align_corners=False
        ).squeeze()

    depth = prediction.cpu().numpy()
    depth = cv2.normalize(depth, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)
    depth_img = cv2.cvtColor(depth, cv2.COLOR_GRAY2BGR)
    return depth_img

# ---------------------- Canny Edges ----------------------
def get_edges(image_path, resize=(512,416)):
    img = cv2.imread(image_path)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    edges = cv2.Canny(gray, 100, 200)
    edges_color = cv2.cvtColor(edges, cv2.COLOR_GRAY2BGR)
    edges_color = cv2.resize(edges_color, resize)
    return edges_color

# ---------------------- Semantic Segmentation ----------------------
deeplab_model = torchvision.models.segmentation.deeplabv3_resnet101(pretrained=True).eval().to(device)
seg_transform = torchvision.transforms.Compose([
    torchvision.transforms.ToTensor(),
    torchvision.transforms.Normalize(mean=[0.485,0.456,0.406], std=[0.229,0.224,0.225])
])

def get_segmentation(image_path, resize=(512,416)):
    img = Image.open(image_path).convert("RGB")
    input_tensor = seg_transform(img).unsqueeze(0).to(device)
    with torch.no_grad():
        output = deeplab_model(input_tensor)['out'][0]
    seg_map = output.argmax(0).byte().cpu().numpy()
    seg_color = cv2.applyColorMap(seg_map, cv2.COLORMAP_JET)
    seg_color = cv2.resize(seg_color, resize)
    return seg_color

# Load individual ControlNets (use only those you want)
controlnet_depth = ControlNetModel.from_pretrained("lllyasviel/sd-controlnet-depth").to(device)
controlnet_edges = ControlNetModel.from_pretrained("lllyasviel/sd-controlnet-canny").to(device)
controlnet_seg = ControlNetModel.from_pretrained("lllyasviel/sd-controlnet-seg").to(device)

# Example: dynamically choose which ControlNets to use
def create_pipeline(use_depth=True, use_edges=True, use_seg=True):
    controlnets = []
    if use_depth: controlnets.append(controlnet_depth)
    if use_edges: controlnets.append(controlnet_edges)
    if use_seg: controlnets.append(controlnet_seg)

    pipe = StableDiffusionControlNetPipeline.from_pretrained(
        "runwayml/stable-diffusion-v1-5",
        controlnet=controlnets
    ).to(device)

    pipe.enable_attention_slicing()
    if device.type == "cuda":
        pipe.enable_xformers_memory_efficient_attention()

    return pipe

def generate_design(layout_path, prompt, output_path="generated.png",
                    use_depth=True, use_edges=True, use_seg=True):

    feature_maps = []
    if use_depth:
        depth_map = get_depth_map(layout_path)
        feature_maps.append(Image.fromarray(depth_map))
    if use_edges:
        edges_map = get_edges(layout_path)
        feature_maps.append(Image.fromarray(edges_map))
    if use_seg:
        seg_map = get_segmentation(layout_path)
        feature_maps.append(Image.fromarray(seg_map))

    # Create pipeline with only selected controlnets
    pipe = create_pipeline(use_depth, use_edges, use_seg)

    # Generate
    result = pipe(
        prompt=prompt,
        image=feature_maps,
        num_inference_steps=25,
        guidance_scale=8.5
    )

    img = result.images[0]
    img.save(output_path)
    print(f" Saved generated image: {output_path}")
    return img

def show_images_side_by_side(images, titles=None, figsize=(15,5)):
    plt.figure(figsize=figsize)
    for i, img in enumerate(images):
        plt.subplot(1, len(images), i+1)
        plt.imshow(img)
        if titles: plt.title(titles[i])
        plt.axis("off")
    plt.show()

# @title Sample 1
layout_image = "rooms_1.jpg"
prompt = "modern living room with luxurious design and warm open sun light entering thr room from right side"

generated_img = generate_design(layout_image, prompt,
                                use_depth=True, use_edges=True, use_seg=True)

# Show original + generated
show_images_side_by_side([Image.open(layout_image), generated_img],
                        titles=["Original Layout", "Generated Interior"])

# @title Sample 2
layout_image = "rooms_1.jpg"
prompt = "cozy indian bedroom in the himilayas on the back size of bed , use a window instead of the photoframe. also include all stone furniture"

generated_img = generate_design(layout_image, prompt,
                                use_depth=True, use_edges=False, use_seg=True)

show_images_side_by_side([Image.open(layout_image), generated_img],
                        titles=["Original Layout", "Generated Interior"])

# @title Modular design
# ===================================================
# Advanced Modular AI Interior Design Pipeline
# ===================================================
# Features:
# - Depth (MiDaS)
# - Semantic segmentation (DeepLabv3)
# - Canny edges
# - Normal maps (from depth gradient)
# - Instance segmentation (Mask R-CNN)
# - Room layout skeleton (Hough lines)
# - Text-guided instance selection
# - Modular multi-ControlNet pipeline
# - Handles dynamic input/output map sizes

# ---------------------------
# Imports & Device
# ---------------------------
import os, math, time
import torch, torchvision
import numpy as np
import cv2
from PIL import Image
import matplotlib.pyplot as plt
from torchvision import transforms as T
from diffusers import StableDiffusionControlNetPipeline, ControlNetModel

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

# ---------------------------
# Helpers
# ---------------------------
def pil_to_cv2(img_pil): return cv2.cvtColor(np.array(img_pil), cv2.COLOR_RGB2BGR)
def cv2_to_pil(img_cv2): return Image.fromarray(cv2.cvtColor(img_cv2, cv2.COLOR_BGR2RGB))

def ensure_size(img_cv2, target_size):
    """Resize image to target_size if larger than target_size, else keep original."""
    H, W = img_cv2.shape[:2]
    max_h, max_w = target_size
    if H > max_h or W > max_w:
        return cv2.resize(img_cv2, (max_w, max_h), interpolation=cv2.INTER_AREA)
    else:
        return img_cv2.copy()

# ---------------------------
# 1) DEPTH MAP (MiDaS)
# ---------------------------
print("Loading MiDaS...")
midas = torch.hub.load("intel-isl/MiDaS", "DPT_Hybrid").to(device).eval()
midas_transforms = torch.hub.load("intel-isl/MiDaS", "transforms")
midas_transform = getattr(midas_transforms, "dpt_transform", midas_transforms.default_transform)

def get_depth_map(img_path, out_size=(512,512)):
    pil = Image.open(img_path).convert("RGB")
    img_np = np.array(pil)
    inp = midas_transform(img_np).to(device)
    with torch.no_grad():
        pred = midas(inp)
        pred = torch.nn.functional.interpolate(
            pred.unsqueeze(1),
            size=img_np.shape[:2],
            mode="bicubic",
            align_corners=False
        ).squeeze()
    depth = cv2.normalize(pred.cpu().numpy(), None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)
    depth_bgr = cv2.cvtColor(depth, cv2.COLOR_GRAY2BGR)
    depth_bgr = ensure_size(depth_bgr, out_size)
    return depth_bgr

# ---------------------------
# 2) NORMAL MAP (from depth)
# ---------------------------
def get_normal_map_from_depth(depth_bgr):
    depth = cv2.cvtColor(depth_bgr, cv2.COLOR_BGR2GRAY).astype(np.float32)/255.0
    dzdx = cv2.Sobel(depth, cv2.CV_32F, 1, 0, 3)
    dzdy = cv2.Sobel(depth, cv2.CV_32F, 0, 1, 3)
    nx = -dzdx; ny = -dzdy; nz = np.ones_like(depth)
    norm = np.sqrt(nx*nx + ny*ny + nz*nz) + 1e-8
    nx/=norm; ny/=norm; nz/=norm
    normal_vis = (np.stack([(nx+1)/2, (ny+1)/2, (nz+1)/2], axis=-1)*255).astype(np.uint8)
    return cv2.cvtColor(normal_vis, cv2.COLOR_RGB2BGR)

# ---------------------------
# 3) CANNY EDGES
# ---------------------------
def get_edges(img_path, out_size=(512,512), low=100, high=200):
    img = cv2.imread(img_path)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    edges = cv2.Canny(gray, low, high)
    edges_bgr = cv2.cvtColor(edges, cv2.COLOR_GRAY2BGR)
    return ensure_size(edges_bgr, out_size)

# ---------------------------
# 4) SEMANTIC SEGMENTATION (DeepLabv3)
# ---------------------------
print("Loading DeepLabv3...")
deeplab = torchvision.models.segmentation.deeplabv3_resnet101(pretrained=True).eval().to(device)
seg_preprocess = T.Compose([T.ToTensor(), T.Normalize(mean=[0.485,0.456,0.406], std=[0.229,0.224,0.225])])
def get_semantic_segmentation(img_path, out_size=(512,512), colormap=cv2.COLORMAP_JET):
    pil = Image.open(img_path).convert("RGB")
    inp = seg_preprocess(pil).unsqueeze(0).to(device)
    with torch.no_grad():
        out = deeplab(inp)['out'][0]
    seg = out.argmax(0).byte().cpu().numpy()
    seg_color = cv2.applyColorMap(seg.astype(np.uint8), colormap)
    return ensure_size(seg_color, out_size), seg

# ---------------------------
# 5) INSTANCE SEGMENTATION (Mask R-CNN)
# ---------------------------
print("Loading Mask R-CNN...")
maskrcnn = torchvision.models.detection.maskrcnn_resnet50_fpn(pretrained=True).eval().to(device)
mask_transform = T.Compose([T.ToTensor()])
COCO_INSTANCE_CATEGORY_NAMES = [
    '__background__','person','bicycle','car','motorcycle','airplane','bus','train','truck','boat','traffic light',
    'fire hydrant','N/A','stop sign','parking meter','bench','bird','cat','dog','horse','sheep','cow','elephant','bear',
    'zebra','giraffe','N/A','backpack','umbrella','N/A','N/A','handbag','tie','suitcase','frisbee','skis','snowboard','sports ball',
    'kite','baseball bat','baseball glove','skateboard','surfboard','tennis racket','bottle','N/A','wine glass','cup','fork','knife',
    'spoon','bowl','banana','apple','sandwich','orange','broccoli','carrot','hot dog','pizza','donut','cake','chair','couch','potted plant',
    'bed','dining table','N/A','toilet','N/A','tv','laptop','mouse','remote','keyboard','cell phone','microwave','oven','toaster','sink',
    'refrigerator','N/A','book','clock','vase','scissors','teddy bear','hair drier','toothbrush'
]

def get_instance_masks(img_path, score_thresh=0.6, out_size=(512,512)):
    pil = Image.open(img_path).convert("RGB")
    img_cv = pil_to_cv2(pil)
    inp = mask_transform(pil).to(device)
    with torch.no_grad():
        outputs = maskrcnn([inp])[0]
    masks = outputs['masks']; labels = outputs['labels'].cpu().numpy()
    scores = outputs['scores'].cpu().numpy(); boxes = outputs['boxes'].cpu().numpy()
    H,W = img_cv.shape[:2]; instances=[]; vis=np.zeros_like(img_cv)
    for i in range(len(masks)):
        if scores[i]<score_thresh: continue
        mask=(masks[i,0].cpu().numpy()>0.5).astype(np.uint8)*255
        mask_resized=cv2.resize(mask, out_size, interpolation=cv2.INTER_NEAREST).astype(bool)
        label=COCO_INSTANCE_CATEGORY_NAMES[labels[i]]
        instances.append({'mask':mask_resized,'label':label,'score':float(scores[i]),'bbox':boxes[i].tolist()})
        color=tuple(np.random.randint(50,230,size=3).tolist())
        vis[mask>0]=color
    vis=ensure_size(vis,out_size)
    return vis, instances

# ---------------------------
# 6) ROOM LAYOUT SKELETON (Hough lines)
# ---------------------------
def get_room_layout_skeleton(img_path, out_size=(512,512)):
    img=cv2.imread(img_path); gray=cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    edges=cv2.Canny(gray,50,150)
    lines=cv2.HoughLinesP(edges,rho=1,theta=np.pi/180,threshold=80,minLineLength=50,maxLineGap=10)
    sk=np.zeros_like(img); line_list=[]
    if lines is not None:
        for l in lines:
            x1,y1,x2,y2=l[0]; line_list.append((int(x1),int(y1),int(x2),int(y2)))
            cv2.line(sk,(x1,y1),(x2,y2),(0,255,0),2)
    sk=ensure_size(sk,out_size)
    return sk,line_list

# ---------------------------
# 7) TEXT-GUIDED INSTANCE SELECTION
# ---------------------------
def select_instances_by_text(instances,text_label_list):
    if isinstance(text_label_list,str): text_label_list=[text_label_list.lower()]
    combined=None; selected=[]
    for inst in instances:
        if inst['label'].lower() in text_label_list:
            if combined is None: combined=inst['mask'].copy()
            else: combined|=inst['mask']
            selected.append(inst)
    if combined is None:
        size0=instances[0]['mask'].shape if len(instances)>0 else (512,512)
        combined=np.zeros(size0,dtype=bool)
    return combined,selected

# ---------------------------
# 8) CONTROLNETS
# ---------------------------
print("Loading ControlNets...")
controlnet_depth=ControlNetModel.from_pretrained("lllyasviel/sd-controlnet-depth").to(device)
controlnet_canny=ControlNetModel.from_pretrained("lllyasviel/sd-controlnet-canny").to(device)
try:
    controlnet_seg=ControlNetModel.from_pretrained("lllyasviel/sd-controlnet-seg").to(device)
except:
    print("Seg-ControlNet unavailable, skipping"); controlnet_seg=None

def build_pipe(use_depth=True,use_edges=True,use_seg=True,use_instance=False):
    controls=[]
    if use_depth: controls.append(controlnet_depth)
    if use_edges: controls.append(controlnet_canny)
    if use_seg and controlnet_seg is not None: controls.append(controlnet_seg)
    pipe=StableDiffusionControlNetPipeline.from_pretrained("runwayml/stable-diffusion-v1-5",controlnet=controls).to(device)
    pipe.enable_attention_slicing()
    if device.type=="cuda":
        try: pipe.enable_xformers_memory_efficient_attention()
        except: pass
    return pipe

# ---------------------------
# 9) MASTER GENERATION FUNCTION
# ---------------------------
def generate_controlled_interior(
    layout_path,prompt,out_path="generated.png",
    use_depth=True,use_edges=True,use_seg=True,use_instance=False,
    instance_target_label=None,num_inference_steps=20,guidance_scale=7.5,
    map_size=(620,512)
):
    # --- Extract feature maps ---
    maps=[]; map_names=[]
    # Dynamically scale each control map to input image size if smaller than map_size
    img_pil=Image.open(layout_path).convert("RGB")
    H_img,W_img=img_pil.size
    scale_size=(min(H_img,map_size[0]),min(W_img,map_size[1]))

    if use_depth:
        depth=get_depth_map(layout_path,out_size=scale_size)
        maps.append(Image.fromarray(cv2.cvtColor(depth,cv2.COLOR_BGR2RGB))); map_names.append("depth")
    if use_edges:
        edges=get_edges(layout_path,out_size=scale_size)
        maps.append(Image.fromarray(cv2.cvtColor(edges,cv2.COLOR_BGR2RGB))); map_names.append("canny")
    if use_seg:
        seg_color,seg_raw=get_semantic_segmentation(layout_path,out_size=scale_size)
        maps.append(Image.fromarray(cv2.cvtColor(seg_color,cv2.COLOR_BGR2RGB))); map_names.append("seg")

    instance_vis=None; selected_instances=None
    if use_instance:
        vis,instances=get_instance_masks(layout_path,score_thresh=0.5,out_size=scale_size)
        instance_vis=vis
        if instance_target_label:
            combined_mask,selected_instances=select_instances_by_text(instances,instance_target_label)
            instance_mask_img=cv2.cvtColor((combined_mask.astype(np.uint8)*255),cv2.COLOR_GRAY2BGR)
            maps.append(Image.fromarray(cv2.cvtColor(instance_mask_img,cv2.COLOR_BGR2RGB)))
            map_names.append("instance_mask")
        else:
            maps.append(Image.fromarray(cv2.cvtColor(instance_vis,cv2.COLOR_BGR2RGB)))
            map_names.append("instances")

    # --- Build pipeline ---
    pipe=build_pipe(use_depth,use_edges,use_seg,use_instance)

    # --- Run generation ---
    # Ensure number of maps == number of controlnets
    maps_for_pipe=maps[:len(pipe.controlnet.nets)]
    print("Maps used:", map_names)
    out=pipe(prompt=prompt,image=maps_for_pipe,num_inference_steps=num_inference_steps,guidance_scale=guidance_scale)
    generated=out.images[0]
    generated.save(out_path)
    print("Saved:",out_path)
    return {"generated_pil":generated,"maps_cv2":{n:pil_to_cv2(maps[i]) for i,n in enumerate(map_names) if i<len(maps)},"instance_vis_cv2":instance_vis,"selected_instances":selected_instances}

# ---------------------------
# 10) VISUALIZATION
# ---------------------------
def show_side_by_side(images_pil,titles=None,figsize=(15,5)):
    plt.figure(figsize=figsize)
    for i,img in enumerate(images_pil):
        plt.subplot(1,len(images_pil),i+1); plt.imshow(img)
        if titles: plt.title(titles[i]); plt.axis('off')
    plt.show()

# ---------------------------
# 11) EXAMPLE USAGE
# ---------------------------
if __name__=="__main__":
    layout="rooms_1.jpg"
    prompt="modern Scandinavian living room, warm wood, minimal furniture"
    res=generate_controlled_interior(
        layout,prompt,out_path="gen_chairs.png",
        use_depth=True,use_edges=True,use_seg=True,use_instance=True,
        instance_target_label="chair",
        num_inference_steps=25,guidance_scale=7.5,
        map_size=(620,512)
    )

    # Show results
    orig=Image.open(layout).convert("RGB")
    imgs=[orig]; titles=["Original"]
    if res['instance_vis_cv2'] is not None:
        imgs.append(cv2_to_pil(res['instance_vis_cv2'])); titles.append("Instance Viz")
    if 'depth' in res['maps_cv2']:
        imgs.append(cv2_to_pil(res['maps_cv2']['depth'])); titles.append("Depth")
    imgs.append(res['generated_pil']); titles.append("Generated")
    show_side_by_side(imgs,titles)

!pip install -q torch torchvision --upgrade
!pip install -q diffusers transformers accelerate safetensors setuptools ftfy
!pip install -q opencv-python-headless pillow matplotlib

import os, math, time
import random
import torch, torchvision
import numpy as np
import cv2
from PIL import Image
import matplotlib.pyplot as plt
from torchvision import transforms as T
from diffusers import StableDiffusionControlNetPipeline, ControlNetModel


# CONFIG
# map_size is (width, height)

DEFAULT_MAP_SIZE = (620, 512)
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# CPU
torch.set_num_threads(2)

# Model choices (for smaller variants on CPU)
MIDAS_MODEL = "MiDaS_small"         # use small for CPU
DEEPLAB_VARIANT = "resnet50"        # deeplabv3_resnet5
MASKRCNN_VARIANT = "maskrcnn_resnet50_fpn"  # heavy but common

print("Device:", DEVICE)


# Helpers

def pil_to_cv2(img_pil): return cv2.cvtColor(np.array(img_pil), cv2.COLOR_RGB2BGR)
def cv2_to_pil(img_cv2): return Image.fromarray(cv2.cvtColor(img_cv2, cv2.COLOR_BGR2RGB))

def ensure_size(img_cv2, target_size):
    """target_size: (max_w, max_h). If image larger than either, resize proportionally to fit within."""
    max_w, max_h = target_size
    H, W = img_cv2.shape[:2]
    scale = min(1.0, min(max_w / float(W), max_h / float(H)))
    if scale < 1.0:
        new_w, new_h = int(W * scale), int(H * scale)
        return cv2.resize(img_cv2, (new_w, new_h), interpolation=cv2.INTER_AREA)
    return img_cv2.copy()


# Model loaders

def load_midas(model_name=MIDAS_MODEL, device=DEVICE):
    print("Loading MiDaS:", model_name)
    midas = torch.hub.load("intel-isl/MiDaS", model_name).to(device).eval()
    midas_transforms = torch.hub.load("intel-isl/MiDaS", "transforms")
    # choosing transform
    midas_transform = getattr(midas_transforms, "dpt_transform", getattr(midas_transforms, "small_transform", midas_transforms.default_transform))
    return midas, midas_transform

def load_deeplab(variant=DEEPLAB_VARIANT, device=DEVICE):
    print("Loading DeepLabv3:", variant)
    if variant == "resnet50":
        model = torchvision.models.segmentation.deeplabv3_resnet50(pretrained=True).eval().to(device)
    else:
        model = torchvision.models.segmentation.deeplabv3_resnet101(pretrained=True).eval().to(device)
    preprocess = T.Compose([T.ToTensor(), T.Normalize(mean=[0.485,0.456,0.406], std=[0.229,0.224,0.225])])
    return model, preprocess

def load_maskrcnn(device=DEVICE):
    print("Loading Mask R-CNN...")
    model = torchvision.models.detection.maskrcnn_resnet50_fpn(pretrained=True).eval().to(device)
    transform = T.Compose([T.ToTensor()])
    return model, transform

# Lazy load so that on CPU we can avoid loading everything at once
midas = midas_transform = None
deeplab = seg_preprocess = None
maskrcnn = mask_transform = None


# 1) DEPTH MAP (MiDaS) - function accepts PIL path or PIL.Image

def get_depth_map(input_image, out_size=DEFAULT_MAP_SIZE, model_name=MIDAS_MODEL):
    global midas, midas_transform
    if midas is None:
        midas, midas_transform = load_midas(model_name, device=DEVICE)
    # accept path or PIL
    if isinstance(input_image, str):
        pil = Image.open(input_image).convert("RGB")
    else:
        pil = input_image.convert("RGB")
    img_np = np.array(pil)
    inp = midas_transform(img_np).to(DEVICE)
    with torch.no_grad():
        pred = midas(inp)
        pred = torch.nn.functional.interpolate(
            pred.unsqueeze(1),
            size=img_np.shape[:2],
            mode="bicubic",
            align_corners=False
        ).squeeze()
    depth = cv2.normalize(pred.cpu().numpy(), None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)
    depth_bgr = cv2.cvtColor(depth, cv2.COLOR_GRAY2BGR)
    return ensure_size(depth_bgr, out_size)


# 2) NORMAL MAP (from depth)

def get_normal_map_from_depth(depth_bgr):
    depth = cv2.cvtColor(depth_bgr, cv2.COLOR_BGR2GRAY).astype(np.float32)/255.0
    dzdx = cv2.Sobel(depth, cv2.CV_32F, 1, 0, 3)
    dzdy = cv2.Sobel(depth, cv2.CV_32F, 0, 1, 3)
    nx = -dzdx; ny = -dzdy; nz = np.ones_like(depth)
    norm = np.sqrt(nx*nx + ny*ny + nz*nz) + 1e-8
    nx/=norm; ny/=norm; nz/=norm
    normal_vis = (np.stack([(nx+1)/2, (ny+1)/2, (nz+1)/2], axis=-1)*255).astype(np.uint8)
    return cv2.cvtColor(normal_vis, cv2.COLOR_RGB2BGR)


# 3) CANNY EDGES (modular params)

def get_edges(input_image, out_size=DEFAULT_MAP_SIZE, low=100, high=200):
    if isinstance(input_image, str):
        img = cv2.imread(input_image)
    else:
        img = pil_to_cv2(input_image)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    edges = cv2.Canny(gray, low, high)
    edges_bgr = cv2.cvtColor(edges, cv2.COLOR_GRAY2BGR)
    return ensure_size(edges_bgr, out_size)


# 4) SEMANTIC SEGMENTATION (DeepLabv3)

def get_semantic_segmentation(input_image, out_size=DEFAULT_MAP_SIZE, colormap=cv2.COLORMAP_JET):
    global deeplab, seg_preprocess
    if deeplab is None:
        deeplab, seg_preprocess = load_deeplab(device=DEVICE)
    pil = Image.open(input_image).convert("RGB") if isinstance(input_image, str) else input_image.convert("RGB")
    inp = seg_preprocess(pil).unsqueeze(0).to(DEVICE)
    with torch.no_grad():
        out = deeplab(inp)['out'][0]
    seg = out.argmax(0).byte().cpu().numpy()
    seg_color = cv2.applyColorMap(seg.astype(np.uint8), colormap)
    return ensure_size(seg_color, out_size), seg


# 5) INSTANCE SEGMENTATION (Mask R-CNN)

COCO_INSTANCE_CATEGORY_NAMES = [
    '__background__','person','bicycle','car','motorcycle','airplane','bus','train','truck','boat','traffic light',
    'fire hydrant','N/A','stop sign','parking meter','bench','bird','cat','dog','horse','sheep','cow','elephant','bear',
    'zebra','giraffe','N/A','backpack','umbrella','N/A','N/A','handbag','tie','suitcase','frisbee','skis','snowboard','sports ball',
    'kite','baseball bat','baseball glove','skateboard','surfboard','tennis racket','bottle','N/A','wine glass','cup','fork','knife',
    'spoon','bowl','banana','apple','sandwich','orange','broccoli','carrot','hot dog','pizza','donut','cake','chair','couch','potted plant',
    'bed','dining table','N/A','toilet','N/A','tv','laptop','mouse','remote','keyboard','cell phone','microwave','oven','toaster','sink',
    'refrigerator','N/A','book','clock','vase','scissors','teddy bear','hair drier','toothbrush'
]

def get_instance_masks(input_image, score_thresh=0.6, out_size=DEFAULT_MAP_SIZE):
    global maskrcnn, mask_transform
    if maskrcnn is None:
        maskrcnn, mask_transform = load_maskrcnn(device=DEVICE)
    pil = Image.open(input_image).convert("RGB") if isinstance(input_image, str) else input_image.convert("RGB")
    img_cv = pil_to_cv2(pil)
    inp = mask_transform(pil).to(DEVICE)
    with torch.no_grad():
        outputs = maskrcnn([inp])[0]
    masks = outputs['masks']; labels = outputs['labels'].cpu().numpy()
    scores = outputs['scores'].cpu().numpy(); boxes = outputs['boxes'].cpu().numpy()
    H,W = img_cv.shape[:2]; instances=[]; vis=np.zeros_like(img_cv)
    for i in range(len(masks)):
        if scores[i]<score_thresh: continue
        mask=(masks[i,0].cpu().numpy()>0.5).astype(np.uint8)*255
        mask_resized=cv2.resize(mask, out_size, interpolation=cv2.INTER_NEAREST).astype(bool)
        label=COCO_INSTANCE_CATEGORY_NAMES[labels[i]]
        instances.append({'mask':mask_resized,'label':label,'score':float(scores[i]),'bbox':boxes[i].tolist()})
        color=tuple([int(x) for x in np.random.randint(50,230,size=3).tolist()])
        vis[mask>0]=color
    vis=ensure_size(vis,out_size)
    return vis, instances


# 6) ROOM LAYOUT SKELETON (Hough lines)

def get_room_layout_skeleton(input_image, out_size=DEFAULT_MAP_SIZE):
    img = cv2.imread(input_image) if isinstance(input_image, str) else pil_to_cv2(input_image)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    edges = cv2.Canny(gray, 50, 150)
    lines = cv2.HoughLinesP(edges, rho=1, theta=np.pi/180, threshold=80, minLineLength=50, maxLineGap=10)
    sk = np.zeros_like(img); line_list=[]
    if lines is not None:
        for l in lines:
            x1,y1,x2,y2 = l[0]
            line_list.append((int(x1),int(y1),int(x2),int(y2)))
            cv2.line(sk,(x1,y1),(x2,y2),(0,255,0),2)
    sk = ensure_size(sk, out_size)
    return sk, line_list


# 7) TEXT-GUIDED INSTANCE SELECTION

def select_instances_by_text(instances, text_label_list):
    if isinstance(text_label_list, str): text_label_list = [text_label_list.lower()]
    combined = None; selected = []
    for inst in instances:
        if inst['label'].lower() in text_label_list:
            if combined is None:
                combined = inst['mask'].copy()
            else:
                combined |= inst['mask']
            selected.append(inst)
    if combined is None:
        size0 = instances[0]['mask'].shape if len(instances) > 0 else DEFAULT_MAP_SIZE[::-1]  # (h,w)
        combined = np.zeros(size0, dtype=bool)
    return combined, selected


# 8) CONTROLNETS (lazy, optional on CPU)

def load_controlnet(name, device=DEVICE):
    try:
        print("Loading ControlNet:", name)
        cn = ControlNetModel.from_pretrained(name)
        return cn.to(device)
    except Exception as e:
        print("ControlNet load failed:", name, e)
        return None

# You can choose to load only the ControlNets you need at runtime to save RAM

CONTROLNET_REGISTRY = {
    "depth": "lllyasviel/sd-controlnet-depth",
    "canny": "lllyasviel/sd-controlnet-canny",
    "seg":   "lllyasviel/sd-controlnet-seg"
}

def build_pipe(control_keys, hf_model="runwayml/stable-diffusion-v1-5", device=DEVICE, low_cpu_mem=False):
    controls = []
    for k in control_keys:
        name = CONTROLNET_REGISTRY.get(k)
        if name:
            cn = load_controlnet(name, device=torch.device("cpu") if device.type=="cpu" else device)
            if cn is not None:
                controls.append(cn)
    # pass list if multiple controlnets
    pipe = StableDiffusionControlNetPipeline.from_pretrained(hf_model, controlnet=controls, safety_checker=None, torch_dtype=torch.float32)
    pipe = pipe.to(device)
    pipe.enable_attention_slicing()
    # try optional offload to reduce peak RAM (if supported)
    try:
        pipe.enable_model_cpu_offload()
    except Exception:
        pass
    return pipe


# 9) MASTER GENERATION (fixed ordering and robust controlnet->maps matching)

def generate_controlled_interior(
    layout_path, prompt, out_path="generated.png",
    use_depth=True, use_edges=True, use_seg=True, use_instance=False,
    instance_target_label=None, num_inference_steps=20, guidance_scale=7.5,
    map_size=DEFAULT_MAP_SIZE, hf_model="runwayml/stable-diffusion-v1-5",
    control_keys_order=None
):
    # map_size is (max_w, max_h)
    if control_keys_order is None:
        control_keys_order = []
        if use_depth: control_keys_order.append("depth")
        if use_edges: control_keys_order.append("canny")
        if use_seg: control_keys_order.append("seg")
        if use_instance: control_keys_order.append("instances")

    maps = []; map_names = []
    img_pil = Image.open(layout_path).convert("RGB")
    W_img, H_img = img_pil.size

    # compute scale_size (width,height) that fits within map_size and original

    max_w, max_h = map_size
    scale_w = min(W_img, max_w); scale_h = min(H_img, max_h)
    scale_size = (scale_w, scale_h)

    # Create maps following a deterministic order (so user can control which ControlNet gets which map)
    if use_depth:
        depth = get_depth_map(img_pil, out_size=scale_size)
        maps.append(Image.fromarray(cv2.cvtColor(depth, cv2.COLOR_BGR2RGB))); map_names.append("depth")
    if use_edges:
        edges = get_edges(img_pil, out_size=scale_size)
        maps.append(Image.fromarray(cv2.cvtColor(edges, cv2.COLOR_BGR2RGB))); map_names.append("canny")
    if use_seg:
        seg_color, seg_raw = get_semantic_segmentation(img_pil, out_size=scale_size)
        maps.append(Image.fromarray(cv2.cvtColor(seg_color, cv2.COLOR_BGR2RGB))); map_names.append("seg")
    instance_vis = None; selected_instances = None
    if use_instance:
        vis, instances = get_instance_masks(img_pil, score_thresh=0.5, out_size=scale_size)
        instance_vis = vis
        if instance_target_label:
            combined_mask, selected_instances = select_instances_by_text(instances, instance_target_label)
            instance_mask_img = cv2.cvtColor((combined_mask.astype(np.uint8)*255), cv2.COLOR_GRAY2BGR)
            maps.append(Image.fromarray(cv2.cvtColor(instance_mask_img, cv2.COLOR_BGR2RGB))); map_names.append("instance_mask")
        else:
            maps.append(Image.fromarray(cv2.cvtColor(instance_vis, cv2.COLOR_BGR2RGB))); map_names.append("instances")

    # Build pipeline with only requested controlnets (order matters)
    pipe = build_pipe(control_keys_order, hf_model=hf_model, device=DEVICE)

    # Robustly match maps -> controlnets: use min length
    try:
        n_cn = len(getattr(pipe.controlnet, "nets", pipe.controlnet))
    except Exception:
        n_cn = len(maps)
    # fallback safe slicing
    maps_for_pipe = maps[:max(1, min(len(maps), n_cn))]

    print("Maps used (names):", map_names)
    # Run generation (be mindful: on CPU this is very slow and may OOM)
    with torch.no_grad():
        out = pipe(prompt=prompt, image=maps_for_pipe, num_inference_steps=num_inference_steps, guidance_scale=guidance_scale)
    generated = out.images[0]
    generated.save(out_path)
    print("Saved:", out_path)

    return {
        "generated_pil": generated,
        "maps_cv2": {n: pil_to_cv2(maps[i]) for i, n in enumerate(map_names) if i < len(maps)},
        "instance_vis_cv2": instance_vis,
        "selected_instances": selected_instances
    }


# 10) Visualization helper

def show_side_by_side(images_pil, titles=None, figsize=(15,5)):
    plt.figure(figsize=figsize)
    for i, img in enumerate(images_pil):
        plt.subplot(1, len(images_pil), i+1); plt.imshow(img)
        if titles: plt.title(titles[i]); plt.axis('off')
    plt.show()


if __name__ == "__main__":
    out = generate_controlled_interior("rooms_1.jpg", "modern indian living room with indian styled furniture", use_depth=True, use_edges=True, use_seg=True, use_instance=True, instance_target_label="chair", num_inference_steps=20, guidance_scale=7.5)

import matplotlib.pyplot as plt
from PIL import Image
import numpy as np

def display_images_from_files(input_image_path, generated_image_pil, title="Original vs. Generated"):
    """
    Displays the original and generated images side-by-side.
    Accepts the file path to the original image and a PIL Image object for the generated one.
    """
    # figure with two subplots side-by-side for input and generated images
    fig, axs = plt.subplots(1, 2, figsize=(12, 6))

    # Load the original image from the file path

    try:
        original_image_pil = Image.open(input_image_path).convert("RGB")
    except FileNotFoundError:
        print(f"Error: Original image file not found at {input_image_path}")
        return

    # Plot the original image on the first subplot
    axs[0].imshow(original_image_pil)
    axs[0].set_title("Original Image")
    axs[0].axis('off')  # Turn off axis labels and ticks

    # Plot the generated image on the second subplot

    axs[1].imshow(generated_image_pil)
    axs[1].set_title("Generated Image")
    axs[1].axis('off')  # Turn off axis labels and ticks

    # title and show the plot
    plt.suptitle(title, fontsize=16)
    plt.tight_layout() # subplot parameters for a tight layout
    plt.show()

#---------------------------------------------------------------------------

if __name__ == "__main__":
    # Provide the path to your original image file
    input_path = "/content/rooms_1.jpg" # Replace with the different image file path
    out_path = "/content/generated.png" # Path to the generated image file

    # Loads the generated image into a PIL object
    try:
        generated_image_pil_object = Image.open(out_path).convert("RGB")
    except FileNotFoundError:
        print(f"Error: Generated image file not found at {out_path}. Please ensure the file exists.")
        # generated_image_pil_object = Image.new('RGB', (100, 100), color = 'red')
        # return # Uncomment this if you want to stop on error

    # Note : Call function with the path and the PIL Image object
    # The second argument must be the PIL Image object, NOT the path string
    display_images_from_files(input_path, generated_image_pil_object)